protocol = "mcc-118"
doc = ""
traits = ["is-daemon"]

[links]
source = "https://github.com/yaq-project/yaqd-mcc"
bugtracker = "https://github.com/yaq-project/yaqd-mcc/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-mcc"

[config]

[state]

[messages]

